services:
  postgres:
    image: postgres:16
    container_name: user-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./users
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_service
      - JWT_SECRET_KEY=your_super_secret_key_change_in_production

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=http://user-service:5000
      - JWT_SECRET_KEY=your_super_secret_key_change_in_production
    ports:
      - "8000:8000"

volumes:
  postgres_data: